repository:
  user: 'postgres'
  password: 'superuser'
  host: 'localhost'
  port: '5432'
  database: 'roles'
  sslmode: 'disable'
<<<<<<< HEAD
pubsub:
  clusterid: 'test-cluster'
  clientid: 'client-id'
  queuename: 'new-queue'
  pingsinterval: 20
  maxunsuccessfulpings: 5
=======
>>>>>>> d8b4b4c0e6f7106fb7300ca14f37fe09382ee674
